import { ArrowUpRight, BrainCircuit, CheckCircle2, CircleAlert, Clock3, Flame, RefreshCw, Sparkles, Target } from 'lucide-react'
import { Link } from 'react-router-dom'

import { Progress } from '@/components/ui/progress'
import { useLearnerToday } from '@/lib/useLearnerToday'

function Metric({ label, value, icon: Icon, accent }: { label: string; value: string; icon: typeof BrainCircuit; accent: string }) {
	return <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><div className={`mb-4 flex h-9 w-9 items-center justify-center rounded-xl ${accent}`}><Icon size={17} /></div><p className="text-xs uppercase tracking-[0.16em] text-slate-400">{label}</p><p className="mt-1 text-2xl font-semibold text-white">{value}</p></div>
}

export default function DashboardPage() {
	const { data, isLoading, error, refresh } = useLearnerToday()
	if (isLoading) return <section className="space-y-6"><div className="h-44 animate-pulse rounded-3xl bg-white/[0.06]" /><div className="grid gap-4 md:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-32 animate-pulse rounded-2xl bg-white/[0.05]" />)}</div></section>
	if (error || !data) return <section className="mx-auto max-w-xl rounded-3xl border border-red-400/20 bg-red-400/10 p-8 text-center"><CircleAlert className="mx-auto mb-4 text-red-300" /><h1 className="text-xl font-semibold text-white">Learner Twin needs a retry</h1><p className="mt-2 text-sm text-slate-300">{error || 'No learner data is available yet.'}</p><button onClick={refresh} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950"><RefreshCw size={15} /> Retry</button></section>

	return <section className="space-y-6">
		<div className="relative overflow-hidden rounded-3xl border border-cyan-300/15 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,0.18),transparent_42%),linear-gradient(135deg,#101b35,#0b1224)] p-6 md:p-8"><div className="relative z-10 flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-sm font-medium text-cyan-300">LEARNOS / TODAY</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white md:text-4xl">Good morning, {data.user.name}.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Your Learner Twin is turning evidence into the next best learning move.</p></div><Link to={data.recommendation.to} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-semibold text-slate-950 transition hover:bg-cyan-300"><Sparkles size={16} /> Start mission <ArrowUpRight size={16} /></Link></div></div>
		<div className="grid gap-4 md:grid-cols-4"><Metric label="Mastery" value={`${data.intelligence.mastery}%`} icon={BrainCircuit} accent="bg-cyan-400/15 text-cyan-300" /><Metric label="Retention" value={`${data.intelligence.retention}%`} icon={Clock3} accent="bg-violet-400/15 text-violet-300" /><Metric label="Confidence" value={`${data.intelligence.confidence}%`} icon={Target} accent="bg-amber-400/15 text-amber-300" /><Metric label="Streak" value={`${data.intelligence.streak} days`} icon={Flame} accent="bg-emerald-400/15 text-emerald-300" /></div>
		<div className="grid gap-6 lg:grid-cols-[1.35fr_0.65fr]"><div className="space-y-6"><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.16em] text-cyan-300">Current learning mission</p><h2 className="mt-2 text-xl font-semibold text-white">{data.mission.title}</h2><p className="mt-1 text-sm text-slate-400">{data.mission.subtitle}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-300">{data.mission.remaining}</span></div><div className="mt-6 flex items-center justify-between text-sm"><span className="text-slate-400">Mastery progress</span><span className="font-semibold text-white">{data.mission.progress}%</span></div><Progress value={data.mission.progress} className="mt-2" /></div>
		<div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-slate-400">Weak concepts</p><h2 className="mt-2 text-xl font-semibold text-white">Where to focus next</h2></div><Link to="/learner-twin" className="text-sm text-cyan-300 hover:text-cyan-200">View twin</Link></div>{data.weakConcepts.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{data.weakConcepts.map((concept) => <div key={concept.name} className="rounded-2xl border border-white/10 bg-slate-950/30 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-medium text-white">{concept.name}</p><p className="mt-1 text-xs text-slate-400">{concept.reason}</p></div><span className="text-sm font-semibold text-amber-300">{concept.mastery}%</span></div><Progress value={concept.mastery} className="mt-3" /><Link to="/practice-lab" className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-cyan-300">{concept.action} <ArrowUpRight size={13} /></Link></div>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-white/15 p-5 text-sm text-slate-400">Complete a quiz to reveal the concepts your Learner Twin should prioritize.</div>}</div></div>
		<div className="space-y-6"><div className="rounded-3xl border border-cyan-300/15 bg-cyan-300/[0.06] p-6"><div className="flex items-center gap-2 text-cyan-300"><Sparkles size={17} /><p className="text-xs font-semibold uppercase tracking-[0.16em]">Recommended next action</p></div><h2 className="mt-4 text-lg font-semibold text-white">{data.recommendation.title}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{data.recommendation.description}</p><Link to={data.recommendation.to} className="mt-5 inline-flex w-full items-center justify-center rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-950">Open action</Link></div><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-300" /><p className="text-xs uppercase tracking-[0.16em] text-slate-400">Upcoming reviews</p></div>{data.upcomingReviews.length ? <div className="mt-4 space-y-3">{data.upcomingReviews.map((review) => <div key={review.id} className="border-b border-white/10 pb-3 last:border-0 last:pb-0"><p className="line-clamp-2 text-sm text-white">{review.question}</p><p className="mt-1 text-xs text-slate-500">{review.source}</p></div>)}</div> : <p className="mt-4 text-sm text-slate-400">No reviews due. Your memory queue is clear.</p>}<Link to="/review" className="mt-4 inline-block text-sm text-cyan-300">Open review queue</Link></div></div></div>
		<div className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex items-center gap-2"><Clock3 size={17} className="text-slate-400" /><h2 className="text-lg font-semibold text-white">Recent learning activity</h2></div>{data.recentActivity.length ? <div className="mt-5 space-y-3">{data.recentActivity.map((item, index) => <div key={item._id || `${item.label}-${index}`} className="flex gap-3"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-cyan-300" /><p className="text-sm text-slate-300">{item.label}</p></div>)}</div> : <p className="mt-4 text-sm text-slate-400">Your learning history will appear here as you work.</p>}</div><div className="rounded-3xl border border-violet-300/15 bg-violet-300/[0.05] p-6"><div className="flex items-center gap-2 text-violet-200"><BrainCircuit size={17} /><h2 className="text-lg font-semibold">AI insight</h2></div><p className="mt-4 text-sm leading-7 text-slate-300">{data.insight}</p><Link to="/analytics" className="mt-5 inline-flex items-center gap-2 text-sm text-violet-200">See the evidence <ArrowUpRight size={15} /></Link></div></div>
	</section>
}