import { useCallback, useEffect, useState } from 'react'
import { ArrowRight, Check, CircleAlert, RefreshCw, Sparkles } from 'lucide-react'
import { api } from '@/lib/api'
import { demoMission } from '@/lib/demoData'

const phases = ['diagnose', 'learn', 'guided_practice', 'independent_practice', 'transfer', 'explain', 'verify', 'review']
const labels: Record<string, string> = { diagnose: 'Diagnose', learn: 'Learn', guided_practice: 'Practice', independent_practice: 'Independence', transfer: 'Transfer', explain: 'Prove', verify: 'Verify', review: 'Review' }

export default function MissionPage() {
	const [mission, setMission] = useState<typeof demoMission | null>(null)
	const [loading, setLoading] = useState(true)
	const [error, setError] = useState<string | null>(null)
	const demo = localStorage.getItem('learnos-demo-mode') === '1'
	const load = useCallback(async () => { setLoading(true); setError(null); if (demo) { setMission(demoMission); setLoading(false); return }; try { const response = await api.get<{ missions?: typeof demoMission[] }>('/api/learning/mission'); setMission(response.data.missions?.[0] || null) } catch { setError('Missions are unavailable right now.') } finally { setLoading(false) } }, [demo])
	useEffect(() => { load() }, [load])
	async function advance() { if (!mission || demo) return; try { const response = await api.post(`/api/learning/mission/${mission._id}/advance`, { lastAttemptCorrect: true, explanationQuality: 80 }); setMission(response.data.mission) } catch { setError('The mission could not advance. Try again.') } }
	if (loading) return <div className="h-96 animate-pulse rounded-3xl bg-white/[0.05]" />
	if (error && !mission) return <div className="rounded-3xl border border-red-400/20 bg-red-400/10 p-8 text-center text-slate-200"><CircleAlert className="mx-auto mb-3 text-red-300" />{error}<button onClick={load} className="mx-auto mt-5 flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950"><RefreshCw size={15} /> Retry</button></div>
	if (!mission) return <div className="rounded-3xl border border-dashed border-white/15 p-10 text-center text-slate-400">No active mission yet. Start a mission from a weak concept on your Learner Twin.</div>
	const currentIndex = phases.indexOf(mission.currentPhase)
	return <section className="space-y-6"><header><p className="text-sm font-medium text-cyan-300">LEARNOS / LEARNING MISSION</p><h1 className="mt-2 text-3xl font-semibold uppercase tracking-tight text-white">{mission.title}</h1><div className="mt-3 flex items-baseline gap-2"><span className="text-3xl font-semibold text-cyan-300">{mission.startScore}%</span><ArrowRight size={17} className="text-slate-500" /><span className="text-3xl font-semibold text-white">{mission.goalScore}%</span><span className="ml-2 text-sm text-slate-400">target mastery</span></div></header>
		<div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-slate-400">Mission timeline</p><p className="mt-1 text-sm text-slate-300">Current stage: <span className="font-semibold text-cyan-300">{labels[mission.currentPhase]}</span></p></div><span className="rounded-full border border-cyan-300/20 px-3 py-1 text-xs text-cyan-200">{currentIndex + 1} / {phases.length}</span></div><div className="mt-8 grid gap-2 md:grid-cols-8">{phases.map((phase, index) => <div key={phase} className="relative"><div className={`flex min-h-20 flex-col items-center justify-center rounded-2xl border px-2 text-center ${index === currentIndex ? 'border-cyan-300 bg-cyan-300/15 text-cyan-100' : index < currentIndex ? 'border-emerald-300/20 bg-emerald-300/[0.06] text-emerald-200' : 'border-white/10 bg-slate-950/20 text-slate-500'}`}>{index < currentIndex ? <Check size={15} /> : <span className="text-xs font-semibold">0{index + 1}</span>}<span className="mt-2 text-xs">{labels[phase]}</span></div>{index < phases.length - 1 ? <span className="absolute right-[-9px] top-10 hidden text-slate-600 md:block">›</span> : null}</div>)}</div></div>
		<div className="grid gap-6 lg:grid-cols-[0.85fr_1.15fr]"><div className="rounded-3xl border border-amber-300/15 bg-amber-300/[0.05] p-6"><div className="flex items-center gap-2 text-amber-200"><Sparkles size={17} /><h2 className="font-semibold">Why are you doing this?</h2></div><p className="mt-4 text-lg leading-8 text-slate-200">{demo ? demoMission.reason : 'This mission is selected from your current evidence and review history.'}</p></div><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><p className="text-xs uppercase tracking-[0.18em] text-slate-400">The next move</p><h2 className="mt-2 text-xl font-semibold text-white">{labels[mission.currentPhase]} the concept</h2><p className="mt-3 text-sm leading-6 text-slate-400">LEARNOS will adjust the next intervention from your answer quality, explanation, confidence, and retrieval result.</p><button onClick={advance} disabled={demo} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:cursor-default disabled:opacity-70">{demo ? 'Demo stage active' : 'Complete stage'} <ArrowRight size={15} /></button></div></div>
	</section>
}