import { useCallback, useEffect, useState } from 'react'
import { CalendarClock, CheckCircle2, CircleAlert, Flame, RefreshCw } from 'lucide-react'
import { api } from '@/lib/api'
import { demoReviews } from '@/lib/demoData'

type Review = typeof demoReviews[number]
export default function ReviewCenterPage() {
	const [reviews, setReviews] = useState<Review[]>([])
	const [loading, setLoading] = useState(true)
	const [error, setError] = useState<string | null>(null)
	const demo = localStorage.getItem('learnos-demo-mode') === '1'
	const load = useCallback(async () => { setLoading(true); setError(null); if (demo) { setReviews(demoReviews); setLoading(false); return }; try { setReviews((await api.get<{ reviews?: Review[] }>('/api/learning/review')).data.reviews || []) } catch { setError('Review schedule could not be loaded.') } finally { setLoading(false) } }, [demo])
	useEffect(() => { load() }, [load])
	if (loading) return <div className="space-y-4">{[1, 2, 3].map((item) => <div key={item} className="h-32 animate-pulse rounded-3xl bg-white/[0.05]" />)}</div>
	if (error) return <div className="rounded-3xl border border-red-400/20 bg-red-400/10 p-8 text-center text-slate-200"><CircleAlert className="mx-auto mb-3 text-red-300" />{error}<button onClick={load} className="mx-auto mt-5 flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950"><RefreshCw size={15} /> Retry</button></div>
	return <section className="space-y-6"><header><p className="text-sm font-medium text-cyan-300">LEARNOS / REVIEW CENTER</p><h1 className="mt-2 text-3xl font-semibold text-white">Remember what matters next.</h1><p className="mt-2 text-sm text-slate-400">Reviews are scheduled from mastery, confidence calibration, and misconception evidence.</p></header><div className="grid gap-4 md:grid-cols-4"><div className="rounded-2xl border border-cyan-300/20 bg-cyan-300/[0.06] p-5"><CalendarClock className="text-cyan-300" /><p className="mt-4 text-xs uppercase tracking-[0.15em] text-slate-400">Due today</p><p className="mt-1 text-3xl font-semibold text-white">{reviews.length}</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><Flame className="text-amber-300" /><p className="mt-4 text-xs uppercase tracking-[0.15em] text-slate-400">Upcoming</p><p className="mt-1 text-3xl font-semibold text-white">4</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><CheckCircle2 className="text-emerald-300" /><p className="mt-4 text-xs uppercase tracking-[0.15em] text-slate-400">Mastered</p><p className="mt-1 text-3xl font-semibold text-white">1</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><CircleAlert className="text-violet-300" /><p className="mt-4 text-xs uppercase tracking-[0.15em] text-slate-400">Reinforce</p><p className="mt-1 text-3xl font-semibold text-white">2</p></div></div><div className="space-y-3">{reviews.length ? reviews.map((review) => <article key={review._id} className="rounded-3xl border border-white/10 bg-white/[0.04] p-5 transition hover:border-cyan-300/30"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs uppercase tracking-[0.15em] text-cyan-300">Due today · {review.conceptId?.name}</p><h2 className="mt-2 text-lg font-semibold text-white">{review.previousQuestion}</h2><p className="mt-3 text-sm text-slate-400">Why this is here: {review.previousMisconception}</p></div><button className="h-fit rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950">Start retrieval</button></div></article>) : <div className="rounded-3xl border border-dashed border-white/15 p-10 text-center text-slate-400">Your review queue is clear. New reviews appear as evidence is collected.</div>}</div></section>
}